server.port=${PORT:8080}
spring.jackson.serialization.write-dates-as-timestamps=false
app.passcode=${APP_PASSCODE}
app.clear-schedule-on-startup=${CLEAR_NANAS_SCHEDULE:false}

spring.datasource.url=${DB_URL}
spring.jpa.hibernate.ddl-auto=update
